<?php
/**
 * PDF report generator.
 *
 * Generates printable HTML/PDF reports for daily entries and summaries.
 * Uses browser print functionality for PDF generation.
 *
 * @package MultiStoreCashManager
 * @since   1.0.0
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * MSCM_PDF_Generator class.
 *
 * @since 1.0.0
 */
class MSCM_PDF_Generator {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'admin_post_mscm_print_report', array( $this, 'handle_print_request' ) );
	}

	/**
	 * Handle print report request.
	 */
	public function handle_print_request() {
		// Verify nonce.
		$nonce = sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ?? '' ) );
		if ( ! wp_verify_nonce( $nonce, 'mscm_print_report' ) ) {
			wp_die( esc_html__( 'Security check failed.', 'multi-store-cash-manager' ) );
		}

		if ( ! current_user_can( 'mscm_view_reports' ) && ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Permission denied.', 'multi-store-cash-manager' ) );
		}

		$type      = sanitize_text_field( $_GET['type'] ?? 'eod' );
		$store_id  = absint( $_GET['store_id'] ?? 0 );
		$date_from = sanitize_text_field( $_GET['date_from'] ?? wp_date( 'Y-m-01' ) );
		$date_to   = sanitize_text_field( $_GET['date_to'] ?? wp_date( 'Y-m-d' ) );

		$report = MSCM()->reports->generate( $type, $store_id, $date_from, $date_to );

		$this->render_print_view( $report );
		exit;
	}

	/**
	 * Render the printable report view.
	 *
	 * @param array $report Report data.
	 */
	private function render_print_view( $report ) {
		$currency = get_option( 'mscm_currency', 'R' );
		$site     = get_bloginfo( 'name' );
		?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php echo esc_html( $report['title'] ?? __( 'Report', 'multi-store-cash-manager' ) ); ?></title>
	<style>
		* { box-sizing: border-box; margin: 0; padding: 0; }
		body { font-family: Arial, sans-serif; font-size: 12px; color: #333; padding: 20px; }
		h1 { font-size: 18px; margin-bottom: 5px; }
		h2 { font-size: 14px; margin: 15px 0 8px; }
		.header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 20px; }
		.meta { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 11px; color: #666; }
		table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
		th { background: #2563eb; color: white; padding: 6px 8px; text-align: left; }
		td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
		tr:nth-child(even) td { background: #f9fafb; }
		.totals-row td { font-weight: bold; background: #dbeafe; border-top: 2px solid #2563eb; }
		.text-right { text-align: right; }
		.negative { color: #ef4444; }
		.positive { color: #10b981; }
		.signature-section { margin-top: 40px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
		.signature-line { border-top: 1px solid #333; padding-top: 5px; margin-top: 40px; font-size: 11px; }
		@media print {
			body { padding: 10px; }
			.no-print { display: none; }
			button { display: none; }
		}
	</style>
</head>
<body>
	<div class="no-print" style="text-align:center;margin-bottom:20px;">
		<button onclick="window.print();" style="background:#2563eb;color:white;border:none;padding:10px 20px;border-radius:4px;cursor:pointer;font-size:14px;">
			🖨️ <?php esc_html_e( 'Print / Save as PDF', 'multi-store-cash-manager' ); ?>
		</button>
		<button onclick="window.close();" style="background:#6b7280;color:white;border:none;padding:10px 20px;border-radius:4px;cursor:pointer;font-size:14px;margin-left:10px;">
			✕ <?php esc_html_e( 'Close', 'multi-store-cash-manager' ); ?>
		</button>
	</div>

	<div class="header">
		<h1><?php echo esc_html( $report['title'] ); ?></h1>
		<div><?php echo esc_html( $site ); ?></div>
	</div>

	<div class="meta">
		<div>
			<?php
			echo esc_html(
				sprintf(
					/* translators: 1: start date, 2: end date */
					__( 'Period: %1$s to %2$s', 'multi-store-cash-manager' ),
					$report['date_from'] ?? '',
					$report['date_to'] ?? ''
				)
			);
			?>
		</div>
		<div>
			<?php
			echo esc_html(
				sprintf(
					/* translators: 1: generated date, 2: generated by user */
					__( 'Generated: %1$s by %2$s', 'multi-store-cash-manager' ),
					$report['generated_at'] ?? current_time( 'mysql' ),
					$report['generated_by'] ?? ''
				)
			);
			?>
		</div>
	</div>

		<?php
		if ( 'eod' === $report['type'] && ! empty( $report['entries'] ) ) {
			$this->render_eod_table( $report, $currency );
		} elseif ( 'consolidated' === $report['type'] && ! empty( $report['stores'] ) ) {
			$this->render_consolidated_table( $report, $currency );
		} elseif ( 'targets' === $report['type'] && ! empty( $report['rows'] ) ) {
			$this->render_targets_table( $report, $currency );
		}
		?>

	<div class="signature-section">
		<div>
			<div class="signature-line"><?php esc_html_e( 'Prepared by:', 'multi-store-cash-manager' ); ?></div>
			<div class="signature-line"><?php esc_html_e( 'Date:', 'multi-store-cash-manager' ); ?></div>
		</div>
		<div>
			<div class="signature-line"><?php esc_html_e( 'Verified by:', 'multi-store-cash-manager' ); ?></div>
			<div class="signature-line"><?php esc_html_e( 'Date:', 'multi-store-cash-manager' ); ?></div>
		</div>
	</div>
</body>
</html>
		<?php
	}

	/**
	 * Render EOD entries table for print.
	 *
	 * @param array  $report   Report data.
	 * @param string $currency Currency symbol.
	 */
	private function render_eod_table( $report, $currency ) {
		?>
		<table>
			<thead>
				<tr>
					<th><?php esc_html_e( 'Date', 'multi-store-cash-manager' ); ?></th>
					<th><?php esc_html_e( 'Store', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Total Cash', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Credit Card', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'EFT', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Total Sales', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Discrepancy', 'multi-store-cash-manager' ); ?></th>
					<th><?php esc_html_e( 'Status', 'multi-store-cash-manager' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $report['entries'] as $entry ) : ?>
					<tr>
						<td><?php echo esc_html( $entry->entry_date ); ?></td>
						<td><?php echo esc_html( $entry->store_name ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $entry->total_cash, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $entry->credit_card, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $entry->eft, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $entry->total_sales, 2 ) ); ?></td>
						<td class="text-right <?php echo floatval( $entry->discrepancy ) < 0 ? 'negative' : ( floatval( $entry->discrepancy ) > 0 ? 'positive' : '' ); ?>">
							<?php echo esc_html( $currency . number_format( $entry->discrepancy, 2 ) ); ?>
						</td>
						<td><?php echo esc_html( $entry->status ); ?></td>
					</tr>
				<?php endforeach; ?>
				<tr class="totals-row">
					<td colspan="2"><?php esc_html_e( 'TOTALS', 'multi-store-cash-manager' ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['total_cash'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['credit_card'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['eft'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['total_sales'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['discrepancy'], 2 ) ); ?></td>
					<td></td>
				</tr>
			</tbody>
		</table>
		<?php
	}

	/**
	 * Render consolidated report table for print.
	 *
	 * @param array  $report   Report data.
	 * @param string $currency Currency symbol.
	 */
	private function render_consolidated_table( $report, $currency ) {
		?>
		<table>
			<thead>
				<tr>
					<th><?php esc_html_e( 'Store', 'multi-store-cash-manager' ); ?></th>
					<th><?php esc_html_e( 'Location', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Total Sales', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Cash', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Credit Card', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'EFT', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Entries', 'multi-store-cash-manager' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $report['stores'] as $store ) : ?>
					<tr>
						<td><?php echo esc_html( $store->store_name ); ?></td>
						<td><?php echo esc_html( $store->location ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $store->total_sales, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $store->total_cash, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $store->total_credit, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $store->total_eft, 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $store->entry_count ); ?></td>
					</tr>
				<?php endforeach; ?>
				<tr class="totals-row">
					<td colspan="2"><?php esc_html_e( 'TOTALS', 'multi-store-cash-manager' ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['total_sales'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['total_cash'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['total_credit'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $currency . number_format( $report['totals']['total_eft'], 2 ) ); ?></td>
					<td class="text-right"><?php echo esc_html( $report['totals']['entry_count'] ); ?></td>
				</tr>
			</tbody>
		</table>
		<?php
	}

	/**
	 * Render targets report table for print.
	 *
	 * @param array  $report   Report data.
	 * @param string $currency Currency symbol.
	 */
	private function render_targets_table( $report, $currency ) {
		?>
		<table>
			<thead>
				<tr>
					<th><?php esc_html_e( 'Store', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Target', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Actual', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Remaining', 'multi-store-cash-manager' ); ?></th>
					<th class="text-right"><?php esc_html_e( 'Progress', 'multi-store-cash-manager' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $report['rows'] as $row ) : ?>
					<tr>
						<td><?php echo esc_html( $row['store_name'] ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $row['target'], 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $row['actual'], 2 ) ); ?></td>
						<td class="text-right"><?php echo esc_html( $currency . number_format( $row['remaining'], 2 ) ); ?></td>
						<td class="text-right <?php echo $row['on_track'] ? 'positive' : 'negative'; ?>">
							<?php echo esc_html( $row['percentage'] . '%' ); ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<?php
	}
}
